apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx-container
          image: nginx:latest
          ports:
            - containerPort: 80

         
# kubectl apply -f
# kubectl get pods
# kubectl get nodes
# kubectl get [deployments/rs/ns/services]
# kubectl logs <podsname>
# kubectl describe <podsname> {state of podd}
# minikube start {starts the cluster}
# minikube